### ISSUE TITLE
Add Ability to override the RequirePermissionAttribute For better readability

### ISSUE THREAD

**Issue by furesoft** [mgernand/AspNetCore.Authorization.Permissions#38]
For Example:
I could write these attribtues:
```
ReadPermission("user")
WritePermission("user")
DeletePermission("user")
```

If it's possible to make this even more readable a resource attribute to the controller could be also added to avoid setting it in the Permission attributes

**Comment by mgernand** [comment]
Hi! 

I am not sure that I understand what you want to achieve. You can create your own attribute types that derive from ```RequirePermissionAttribute```. This attribute can be added to classes and methods (e.g. Controllers and Actions). I added an example to the sample application. have a look at the ```RequireInvoiceDeletePermissionAttribute```.

> If it's possible to make this even more readable a resource attribute to the controller could be also added to avoid setting it in the Permission attributes

What do you mean by that?

**Comment by furesoft** [comment]
> If it's possible to make this even more readable a resource attribute to the controller could be also added to avoid setting it in the Permission attributes

Example:
```
[AuthorizationScope("user")]
public class UserController {
   
   [RequirePermission("read")] 
    public void doSomething() {

    }

}
```

if the class has the AuthorizationScopeAttribute set the RequirePermissionsAttribute uses it to build the complete permission string, eg. user:read
